all:
  vars:
    control_plane_endpoint: 192.168.20.100
    load_balancer_ip_pool:
      - 192.168.20.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.20.110, mac: 'C4:82:E1:06:CA:81', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.20.111, mac: 'C4:82:E1:06:CD:58', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.20.112, mac: 'C4:82:E1:06:E8:85', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.20.113, mac: 'C4:82:E1:06:FB:09', disk: sda, network_interface: eno1}